name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: corepack enable

      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install deps
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      # Runs a set of commands using the runners shell
      - name: Build and Test
        run: npm run test

      - name: Release
        run: pnpx -y semantic-release --branches main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
