name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


permissions:
  contents: read # for checkout

jobs:
  test:
    strategy:
      matrix:
        node: [16, 18, 20]

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install deps
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      # Runs a set of commands using the runners shell
      - name: Build and Test
        run: npm run test

  release:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install deps
        run: pnpm i

      - name: Build
        run: npm run build

      - name: Release
        run: pnpm dlx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
